//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Baseball.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DLGEDITLEAGUE               103
#define IDR_MAINFRAME                   128
#define IDR_BASEBATYPE                  129
#define IDB_UpArrowPressed              130
#define IDB_DownArrow                   131
#define IDB_DownArrowPressed            132
#define IDB_FieldSmall                  133
#define IDB_FieldLineGray1              134
#define IDB_FieldLineGrayComplete       135
#define IDB_FieldGreenLarge             136
#define IDB_FieldSmallGreenComplete     137
#define IDB_ScoreBoard                  138
#define IDB_LightGreen                  139
#define IDB_LightStop                   140
#define IDB_LightCaution                141
#define IDB_UpArrow                     143
#define IDB_Baseballs                   144
#define IDB_FieldLineGray2              146
#define IDB_FieldLineGray3              148
#define IDB_FieldLineGray               149
#define IDB_BITMAP1                     150
#define IDD_LEAGUE1                     151
#define IDD_DIVISION1                   152
#define IDD_ADDTEAMS1                   155
#define IDD_PLAYERS1                    156
#define IDD_TEAM1                       157
#define IDD_SELTEAM1                    158
#define IDD_PITCHERS1                   159
#define IDD_SELLEAGUE1                  160
#define IDB_SPLASH                      161
#define IDD_SPLASH                      162
#define IDD_BATTERS                     163
#define IDD_TEAMHTMLOPTIONS             165
#define IDD_BATTERSCHANCE               166
#define IDD_BATTERSSTATS                167
#define IDR_TOOLBAR1                    167
#define IDD_BATTERSINFO                 168
#define IDD_PITCHERSINFO                170
#define IDD_PITCHERSSTATS               171
#define IDD_PITCHERSCHANCE              172
#define IDD_LEAGUEHTMLOPTIONS           173
#define IDC_LEAGUE1                     1000
#define IDC_CONFERENCE1                 1001
#define IDC_CONFERENCE2                 1002
#define IDC_CONFERENCE3                 1003
#define IDC_CONFERENCE4                 1004
#define IDC_CONFERENCE5                 1005
#define IDC_CONFERENCE6                 1006
#define IDC_CONFERENCE0                 1007
#define IDC_DIVISION1                   1008
#define IDC_DIVISION2                   1009
#define IDC_DIVISION3                   1010
#define IDC_DIVISION4                   1011
#define IDC_DIVISION5                   1012
#define IDC_DIVISION6                   1013
#define IDC_TEAMS1                      1017
#define IDC_DIVISION0                   1018
#define IDC_TEAM0                       1028
#define IDC_SPIN_HITS1                  1031
#define IDC_HITS1                       1032
#define IDC_AB1                         1042
#define IDC_SPIN_AB1                    1043
#define IDC_RUNS1                       1044
#define IDC_SPIN_RUNS1                  1045
#define IDC_RBI1                        1046
#define IDC_SPIN_RBI1                   1047
#define IDC_2B1                         1048
#define IDC_SPIN_2B1                    1049
#define IDC_3B1                         1050
#define IDC_SPIN_3B1                    1051
#define IDC_HR1                         1052
#define IDC_SPIN_HR1                    1053
#define IDC_WALK1                       1054
#define IDC_SPIN_WALK1                  1055
#define IDC_STRIKEOUT1                  1056
#define IDC_SPIN_STRIKOUT1              1057
#define IDC_REACHEDONERROR1             1058
#define IDC_SPIN_REACHEDONERROR1        1059
#define IDC_SACRICIFE1                  1060
#define IDC_SPIN_SACRICIFE1             1061
#define IDC_STOLENBASE1                 1062
#define IDC_SPIN_STOLENBASE1            1063
#define IDC_BATTINGAVERAGE1             1064
#define IDC_SLG1                        1066
#define IDC_ONBASEPERCENT1              1068
#define IDC_COMBO_STEALING1             1070
#define IDC_COMBO_BUNTING1              1071
#define IDC_COMBO_HITRUN1               1072
#define IDC_COMBO_RUNNING1              1073
#define IDC_TEAM1                       1074
#define IDC_SELTEAMLISTBOX1             1075
#define IDPLAYERUPDATE1                 1076
#define IDPLAYERADD1                    1077
#define IDNEW                           1078
#define IDC_COMBO_PLAYERNAME1           1079
#define IDC_CS1                         1080
#define IDC_SPIN_CS1                    1081
#define IDC_WINS1                       1082
#define IDC_SPIN_WINS1                  1083
#define IDC_LOSS1                       1084
#define IDC_SPIN_LOSS1                  1085
#define IDC_SAVES1                      1086
#define IDC_SPIN_SAVES1                 1087
#define IDC_ER1                         1088
#define IDC_SPIN_ER1                    1089
#define IDC_IP1                         1090
#define IDC_ERA1                        1092
#define IDC_TRG1                        1093
#define IDC_STARTER1                    1094
#define IDC_SPIN_STARER1                1095
#define IDC_RELIEF1                     1096
#define IDC_SPIN_RELIEF1                1097
#define IDC_COMBO_HOLD1                 1099
#define IDC_CHANCEBASIC                 1100
#define IDC_CHANCELEFT                  1101
#define IDC_CHANCERIGHT                 1102
#define IDC_CHANCESINGLE                1103
#define IDC_CHANCEDOUBLE                1104
#define IDC_CHANCETRIPLE                1105
#define IDC_CHANCEHR                    1106
#define IDC_PITCHER                     1107
#define IDC_CHANCEWALK                  1107
#define IDC_SPIN_PITCHER                1108
#define IDC_CHANCEDOUBLEPLAY            1108
#define IDC_CATCHER                     1109
#define IDC_SPIN_CATCHER                1110
#define IDC_FIRSTBASE                   1111
#define IDC_SPIN_FIRSTBASE              1112
#define IDC_SECONDBASE                  1113
#define IDC_SPIN_SECONDBASE             1114
#define IDC_SHORTSTOP                   1115
#define IDC_SPIN_SHORTSTOP              1116
#define IDC_THIRDBASE                   1117
#define IDC_SPIN_THIRDBASE              1118
#define IDC_LEFTFIELD                   1119
#define IDC_SPIN_LEFTFIELD              1120
#define IDC_CENTERFIELD                 1121
#define IDC_CHANCESINGLEL               1121
#define IDC_SPIN_CENTERFIELD            1122
#define IDC_CHANCEDOUBLEL               1122
#define IDC_RIGHTFIELD                  1123
#define IDC_CHANCETRIPLEL               1123
#define IDC_SPIN_RIGHTFIELD             1124
#define IDC_CHANCEHRL                   1124
#define IDC_COMBO_BATTERHITS            1125
#define IDC_CHANCEWALKL                 1125
#define IDC_COMBO_PITCHERTHROWS         1126
#define IDC_CHANCEDOUBLEPLAYL           1126
#define IDC_SELLEAGUELISTBOX1           1127
#define IDC_CHANCESINGLER               1127
#define IDC_STARTS1                     1128
#define IDC_CHANCEDOUBLER               1128
#define IDC_SPIN_STARTS1                1129
#define IDC_CHANCETRIPLER               1129
#define IDC_SHORTTEAM1                  1130
#define IDC_CHANCEHRR                   1130
#define IDC_BALLPARK1                   1131
#define IDC_CHANCEWALKR                 1131
#define IDC_GAMES1                      1132
#define IDC_CHANCEDOUBLEPLAYR           1132
#define IDC_SPIN_GAMES1                 1133
#define IDC_COMPLETEGAMES1              1134
#define IDC_SPIN_COMPLETEGAMES1         1135
#define IDC_HBP1                        1136
#define IDC_SPIN_HBP1                   1137
#define IDC_GAMES2                      1138
#define IDC_SPIN_GAMES2                 1139
#define IDC_BIGICON                     1140
#define IDC_ERP                         1141
#define IDC_ERC                         1142
#define IDC_BALK                        1142
#define IDC_ER1B                        1143
#define IDC_WP                          1143
#define IDC_ER2B                        1144
#define IDC_ERSS                        1145
#define IDC_ER3B                        1146
#define IDC_ERLF                        1147
#define IDC_ERCF                        1148
#define IDC_ERRF                        1149
#define IDC_SPIN_ERP                    1150
#define IDC_SPIN_ERC                    1151
#define IDC_SPIN_BALK                   1151
#define IDC_COMBO_PASSBALL              1152
#define IDC_SPIN_WP                     1152
#define IDC_SPIN_ER1B                   1153
#define IDC_COMBO_POWERRIGHT            1154
#define IDC_SPIN_ER2B                   1155
#define IDC_COMBO_POWERLEFT             1156
#define IDC_SPIN_ERSS                   1157
#define IDC_COMBO_OUTARM                1158
#define IDC_SPIN_ER3B                   1159
#define IDC_COMBO_CATCHERARM            1160
#define IDC_SPIN_ERLF                   1161
#define IDC_SLG                         1162
#define IDC_SPIN_ERCF                   1163
#define IDC_INDEX                       1163
#define IDC_BATTINGAVERAGE              1164
#define IDC_SPIN_ERRF                   1165
#define IDC_ONBASEPERCENT               1166
#define IDC_COMBO_RUNNING               1167
#define IDC_BACKGROUNDPICTURE           1167
#define IDC_COMBO_HITRUN                1168
#define IDC_COMBO_BUNTING               1169
#define IDC_COMBOTEXTCOLOR              1169
#define IDC_COMBO_STEALING              1170
#define IDC_COMBOLINKCOLOR              1170
#define IDC_COMBO_TRATE                 1171
#define IDC_COMBOVLINKCOLOR             1171
#define IDC_COMBOBGCOLOR                1172
#define IDC_FIRSTNAME1                  1172
#define IDC_LASTNAME1                   1173
#define ID_FORMS_SCORESHEETFORM         32771
#define ID_FORMS_STATISTCSFORM          32772
#define ID_FORMS_SCORESHEETFORMXTRA     32773
#define ID_VIEW_NORMAL                  32774
#define ID_LEAGUES_ADDLEAGUE            32775
#define ID_LEAGUES_EDITLEAGUE           32776
#define ID_TEAMS_ADDTEAMS               32777
#define ID_TEAMS_EDITTEAMS              32778
#define ID_PLAYERS_ADDPLAYERS           32779
#define ID_STATISTICS_CREATESTATS       32781
#define ID_STATISTICS_UPDATESTATS       32782
#define ID_LEAGUES_ADDLEAGUES           32783
#define ID_LEAGUES_EDITLEAGUES          32784
#define ID_PLAYERS_ADDPITCHERS          32791
#define ID_PLAYERS_DELPLAYERS           32792
#define ID_PLAYERS_DELPITCHERS          32793
#define ID_PLAYERS_EDITLEAGUEBAT        32794
#define ID_PLAYERS_EDITLEAGUEPIT        32795
#define ID_FILE_EXPORTBASETEAMS         32796
#define ID_FILE_EXPORTLEAGUETEAMS       32797
#define ID_FILE_EXPORTHTMLBASETEAMS     32798
#define ID_FILE_EXPORTHTMLLEAGUETEAMS   32799
#define ID_TEAMS_EDITLEAGUETEAMS        32800
#define ID_STATISTICS_HTMLLEAGUESTATS   32801
#define ID_FILE_EXPORTHTMLLEAGUETEAMSALL 32803
#define ID_FILE_EXPORTLEAGUETEAMSALL    32804
#define ID_PLAYERS_ADDEDITBATTERS       32805
#define ID_PLAYERS_ADDEDITPITCHERS      32806
#define ID_LEAGUES_LEAGUEOPTIONSHTML    32807
#define ID_BUTTON32813                  32813
#define ID_BUTTON32814                  32814
#define ID_BUTTON32815                  32815
#define ID_BUTTON32816                  32816
#define ID_BUTTON32817                  32817
#define ID_BUTTON32818                  32818
#define ID_BUTTON32812                  32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
